### ISSUE TITLE
Module name clashing with node-semver port

### ISSUE THREAD

**Issue by MaciejPatro** [python-semver/python-semver#259] opened 2020-05-28 14:17 UTC
Hello,

I have a problem of module name clashing between python-semver and https://pypi.org/project/node-semver/ package.

The problem is that it seems that the other version of package is used by `conan` (C++ package manager) which is quite widely used for C++ projects making python-semver unusable in that environment. 

This creates quite some issues as currently both packages cannot coexist together. 
Do you have any advice how to overcome to problem?

There is also link to issue in https://github.com/podhmo/python-semver/issues/39 node port.

**Comment by tomschr** [comment] 2020-05-31 08:07
Hi @MaciejPatro,

thanks for the heads up about this. That's a really interesting problem. I don't know of any method to rename a module later.

In theory, you could patch one of the `setup.py` files, rename the library, and install it under a different name. However, that's probably cumbersome.

I've did some research and found https://github.com/pypa/packaging-problems/issues/114#issuecomment-348048622 which would not solve the issue, but give some background information. It seems, the problem is known.

**Comment by tomschr** [comment] 2020-12-23 23:15
@MaciejPatro Maciej, just a theoretical question: would it help if you could download this the wheel, let's say, from GitHub instead of PyPI?

**Comment by tomschr** [comment] 2022-12-23 08:07
The node-semver library was renamed/will be renamed in version 0.9.0, see https://github.com/podhmo/python-node-semver/issues/39#issuecomment-919706124

I think we can close this issue now.

**Closed** 2022-12-23 08:08 UTC
Labels: Infra, Question
