### ISSUE TITLE
VersionInfo.isvalid() is missing (referenced in docs)

### ISSUE THREAD

**Issue by kenneaal** [python-semver/python-semver#217] opened 2020-02-14 16:33 UTC
As the subject says. Documentation says semver provides a test for a valid semver string using VersionInfo.isvalid(string), but the method doesn't actually exist in VersionInfo. Version downloaded from pypi is 2.9.0, which is the same version as in the repo here. Forgotten version bump = no update on package repo?

**Comment by tomschr** [comment] 2020-02-15 12:16
@kenneaal I've created a virtual Python environment and install semver from PyPI. I can confirm that there is no `isvalid()` function, although it advertise itself as 2.9.0.

@scls19fr Chould we create a new 2.9.1 release to update the PyPI sources, please?

**Comment by scls19fr** [comment] 2020-02-15 17:24
+1 about creating a new release that fix that
@tomschr I grant you maintainer role on https://pypi.org/manage/project/semver/collaboration/
so you are free to publish such a release and go beyond.
But please still continue to communicate about your plans about this project.

**Comment by tomschr** [comment] 2020-02-15 18:09
@scls19fr Thanks Sébastien! Much appreciated! :+1: 

If I have some time left, I will try to make a release according to your helpful `release-procedure.md` file. The file misses the TestPyPI, so I think I will upload it there first. Would you have a look if I ping you? :wink: 

I'll let you know for sure.

**Comment by scls19fr** [comment] 2020-02-15 19:16
of course @tomschr, I will have a look at it.
Probably not tomorow because I will be very busy.
But I will try to find some time to see this next week.

**Comment by tomschr** [comment] 2020-02-15 20:00
I've opened a new issue #218 which collects all the needed information for creating a new release.

**Comment by tomschr** [comment] 2020-02-16 20:55
The new doc is out, so it was fixed in #219, so closing this issue.

**Closed by tomschr** 2020-02-16 20:55 UTC
Labels: bug
